### ISSUE TITLE
Race condition when two builds pull the same base image

### ISSUE THREAD

**Issue by mmilata** [containerbuildsystem/atomic-reactor#135]
Start two identical builds roughly at the same time:

```
osbs -i test --verbose build --git-url "https://github.com/TomasTomecek/docker-hello-world.git" -u mmilata -c test-image2
osbs -i test --verbose build --git-url "https://github.com/TomasTomecek/docker-hello-world.git" -u mmilata -c test-image3
```

With a bit of luck you'll see for the first instance:

```
2015-06-02 18:31:18,845 - dock.build - INFO - pull base image from registry
2015-06-02 18:31:18,845 - dock.core - INFO - pull image from registry
2015-06-02 18:31:18,845 - dock.core - DEBUG - image = 'fedora:latest', insecure = 'None'
2015-06-02 18:31:21,761 - dock.util - INFO - wait_for_command
2015-06-02 18:31:21,763 - dock.util - DEBUG - Trying to pull repository registry.access.redhat.com/fedora ...
2015-06-02 18:31:29,352 - dock.util - INFO - no more logs
2015-06-02 18:31:29,354 - dock.core - INFO - tag image
2015-06-02 18:31:29,355 - dock.core - DEBUG - image = 'fedora:latest', target_image_name = 'fedora:latest'
2015-06-02 18:31:29,362 - dock.build - DEBUG - image 'fedora:latest' is available
2015-06-02 18:31:29,363 - dock.inner - INFO - running pre-build plugins
```

And for the second:

```
2015-06-02 18:31:21,681 - dock.build - INFO - pull base image from registry
2015-06-02 18:31:21,681 - dock.core - INFO - pull image from registry
2015-06-02 18:31:21,681 - dock.core - DEBUG - image = 'fedora:latest', insecure = 'None'
2015-06-02 18:31:21,708 - dock.util - INFO - wait_for_command
2015-06-02 18:31:22,453 - dock.util - INFO - no more logs
2015-06-02 18:31:22,453 - dock.core - INFO - tag image
2015-06-02 18:31:22,454 - dock.core - DEBUG - image = 'fedora:latest', target_image_name = 'fedora:latest'
Traceback (most recent call last):
  File "/usr/bin/dock", line 9, in <module>
    load_entry_point('dock==1.3.2', 'console_scripts', 'dock')()
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/cli/main.py", line 223, in run
    cli.run()
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/cli/main.py", line 206, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/cli/main.py", line 78, in cli_inside_build
    build_inside(input=args.input, input_args=args.input_arg, substitutions=args.substitute)
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/inner.py", line 291, in build_inside
    build_result = dbw.build_docker_image()
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/inner.py", line 196, in build_docker_image
    insecure=self.parent_registry_insecure)
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/build.py", line 128, in pull_base_image
    response = self.tasker.tag_image(base_image_with_registry, self.base_image, force=True)
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/core.py", line 388, in tag_image
    response = self.d.tag(image, target_image.to_str(tag=False), tag=target_image.tag, force=force)  # returns T
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 934, in tag
    self._raise_for_status(res)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 119, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("could not find image: no such id: fedora:latest")
* Closing connection 0
2015-06-02 20:31:23,381 - osbs.http - DEBUG - closing curl multi: 139781735551056
```

Perhaps it has something to do with https://bugzilla.redhat.com/show_bug.cgi?id=1215934

**Comment by TomasTomecek** [comment]
This looks like it has something to do with docker being single threaded and having issues with parallelism.

**Comment by mmilata** [comment]
I'm unable to reproduce it now. I suspect it might have something to do with DBuildService/osbs#121 which prevents the situation where we to add tag *fedora:latest* to image *fedora:latest* as happens in the original report.

**Comment by TomasTomecek** [comment]
https://github.com/docker/docker/issues/9718#issuecomment-116797397

Looks like a docker issue which should already be fixed.

**Comment by lcarva** [comment]
We tag pulled images with a unique tag to prevent other builds from interfering with it. We also modify the Dockerfile to use the image digest in the orchestrator and propagate this to the workers.
