### ISSUE TITLE
Adjust docker client timeout

### ISSUE THREAD

**Issue by twaugh** [containerbuildsystem/atomic-reactor#457]
```
2016-04-12 09:11:31,786 - atomic_reactor.core - DEBUG - image_id = 'brew-pulp-docker01.internalqa.redhat.com:8888/rhel7:latest'
2016-04-12 09:11:32,456 - atomic_reactor.core - INFO - removing image 'rhel7:latest' from filesystem
2016-04-12 09:11:32,456 - atomic_reactor.core - DEBUG - image_id = 'rhel7:latest'
2016-04-12 09:11:33,137 - atomic_reactor.plugins.remove_built_image - WARNING - failed to remove image rhel7:latest (409: Conflict), ignoring
```

This failure happened because the docker daemon was legitimately taking longer than the default 60s timeout.

We should set the docker client timeout to something more sensible, eg 600s.

**Comment by twaugh** [comment]
@maxamillion I think you've seen this too.

**Comment by twaugh** [comment]
Oh, this isn't a timeout issue but something else. I think the 409 error means there is a container started from that image.

However, I have seen remove_built_image fail with a timeout.

**Comment by vrutkovs** [comment]
@twaugh probably there's a container using ```rhel:7``` image running on the host, I haven't seen that error with ```busybox```

**Comment by twaugh** [comment]
Not necessarily even running I think. I bet it comes from cancelling a build.

**Comment by twaugh** [comment]
This is the timeout I meant:

```
2016-04-22 13:35:26,448 - atomic_reactor.plugin - DEBUG - running plugin 'remove_built_image'
2016-04-22 13:35:26,449 - atomic_reactor.plugin - INFO - running plugin instance with args: '{}'
2016-04-22 13:35:26,449 - atomic_reactor.core - INFO - removing image 'cafcfc72fd65eae4ae1088b8b6f713b317f3566fe18652cebba3a0dc821635b6' from filesystem
2016-04-22 13:35:26,449 - atomic_reactor.core - DEBUG - image_id = 'cafcfc72fd65eae4ae1088b8b6f713b317f3566fe18652cebba3a0dc821635b6'
2016-04-22 13:37:26,593 - atomic_reactor.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomic_reactor/plugin.py", line 203, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/atomic_reactor/plugins/exit_remove_built_image.py", line 38, in run
    self.remove_image(image, force=True)
  File "/usr/lib/python2.7/site-packages/atomic_reactor/plugins/exit_remove_built_image.py", line 58, in remove_image
    self.tasker.remove_image(image, force=force)
  File "/usr/lib/python2.7/site-packages/atomic_reactor/core.py", line 508, in remove_image
    self.d.remove_image(image_id, force=force, noprune=noprune)  # returns None
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/image.py", line 256, in remove_image
    res = self._delete(self._url("/images/{0}", image), params=params)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 120, in _delete
    return self.delete(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 536, in delete
    return self.request('DELETE', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=120)

2016-04-22 13:37:26,593 - atomic_reactor.plugin - WARNING - plugin 'remove_built_image' raised an exception: ReadTimeout(ReadTimeoutError("UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=120)",),)
2016-04-22 13:37:26,593 - atomic_reactor.plugin - INFO - error is not fatal, continuing...
```

**Comment by MartinBasti** [comment]
This is more OPC than docker issue. When dockerd fails higher timeout wont' help
