### ISSUE TITLE
pre_add_labels_in_df fails with "TypeError: a bytes-like object is required, not 'dict'" in python3

### ISSUE THREAD

**Issue by vrutkovs** [containerbuildsystem/atomic-reactor#641]
`atomic-reactor-1.6.19` from Fedora repos crashes on
`-g https://github.com/vrutkovs/docker-hello-world.git -b demo-01 --git-commit 625c193`: 
```
2017-02-07 17:14:31,330 - atomic_reactor.plugins.add_labels_in_dockerfile - INFO - label 'version' not present in base image
2017-02-07 17:14:31,330 - atomic_reactor.plugins.add_labels_in_dockerfile - INFO - setting label '"version"="1.0"'
2017-02-07 17:14:31,330 - atomic_reactor.plugins.add_labels_in_dockerfile - INFO - label 'vcs-type' not present in base image
2017-02-07 17:14:31,330 - atomic_reactor.plugins.add_labels_in_dockerfile - INFO - setting label '"vcs-type"="git"'
2017-02-07 17:14:31,330 - atomic_reactor.plugins.add_labels_in_dockerfile - INFO - label 'authoritative-source-url' not present in base image
2017-02-07 17:14:31,330 - atomic_reactor.plugins.add_labels_in_dockerfile - INFO - setting label '"authoritative-source-url"="docker.com"'
2017-02-07 17:14:31,331 - atomic_reactor.plugins.add_labels_in_dockerfile - INFO - label 'vcs-ref' not present in base image
2017-02-07 17:14:31,332 - atomic_reactor.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/atomic_reactor/plugin.py", line 225, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python3.5/site-packages/atomic_reactor/plugins/pre_add_labels_in_df.py", line 239, in run
    label = '"%s"="%s"' % (escape(key), escape(value))
  File "/usr/lib/python3.5/site-packages/atomic_reactor/plugins/pre_add_labels_in_df.py", line 220, in escape
    return s.translate(env_trans)
TypeError: a bytes-like object is required, not 'dict'
```

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.
